spring:
  application:
    name: athena-insight
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    athena.insight: info
