package com.whu.software.athena.cognitionagent.intent.contract;

public enum AgentErrorCode {
    INVALID_REQUEST,
    MISSING_REQUIRED_FIELD,
    INVALID_ENUM,
    TEXT_TOO_LONG,
    UNSUPPORTED_SOURCE_TYPE,
    UNSUPPORTED_VERSION,
    MODEL_TIMEOUT,
    MODEL_UNAVAILABLE,
    MODEL_OUTPUT_INVALID,
    POLICY_BLOCKED,
    IDEMPOTENCY_CONFLICT,
    GRAPH_VERSION_CONFLICT,
    GRAPH_INTEGRITY_VIOLATION,
    INTERNAL_ERROR
}
