/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.nageoffer.ai.ragent.triage.worker;

import com.nageoffer.ai.ragent.triage.model.*;
import org.springframework.stereotype.Component;

import java.time.Instant;
import java.util.*;

@Component
public class StateReducer {
    private final ReducerCorrectionApplier reducerCorrectionApplier = new ReducerCorrectionApplier();

    public TriageContext execute(TriageContext context){if(context==null)context=new TriageContext();context.ensureCollections();TurnUnderstanding understanding=context.getLatestTurnUnderstanding();StateReducerResult previous=context.getLatestStateReducerResult();StateReducerResult result=previous==null?StateReducerResult.builder().build():copyOf(previous);Map<SlotCode,SlotValue> reducedSlots=copyReducedSlots(result.getReducedSlots(),context.getSlotState());LinkedHashSet<SlotCode> answeredSlots=new LinkedHashSet<>(result.getAnsweredSlots()==null?List.of():result.getAnsweredSlots());LinkedHashSet<SlotCode> pendingCandidates=new LinkedHashSet<>(result.getPendingCandidates()==null?List.of():result.getPendingCandidates());if(pendingCandidates.isEmpty()&&context.getPendingSlots()!=null)pendingCandidates.addAll(context.getPendingSlots());List<CorrectionUnderstanding> correctionLog=new ArrayList<>(result.getCorrectionLog()==null?List.of():result.getCorrectionLog());List<RiskSignalUnderstanding> accumulatedRiskSignals=new ArrayList<>(result.getAccumulatedRiskSignals()==null?List.of():result.getAccumulatedRiskSignals());ComplaintUnderstanding complaintTruth=copyComplaint(result.getComplaintTruth());if(understanding!=null){complaintTruth=mergeComplaintTruth(complaintTruth,understanding.getPrimaryComplaint());mergePrimaryComplaint(reducedSlots,pendingCandidates,complaintTruth);mergeAnsweredSlots(reducedSlots,answeredSlots,pendingCandidates,understanding.getAnsweredSlots());reducerCorrectionApplier.apply(reducedSlots,answeredSlots,pendingCandidates,correctionLog,understanding.getCorrections());mergeRiskSignals(accumulatedRiskSignals,understanding.getRiskSignals());}mergeFacts(reducedSlots,answeredSlots,pendingCandidates,context.getFactHistory(),context.getConversationHistory().size()-1,understanding,complaintTruth);reconcilePendingCandidates(reducedSlots,pendingCandidates);StateReducerResult reduced=StateReducerResult.builder().reducedSlots(reducedSlots).complaintTruth(copyComplaint(complaintTruth)).answeredSlots(new ArrayList<>(answeredSlots)).pendingCandidates(new ArrayList<>(pendingCandidates)).correctionLog(correctionLog).accumulatedRiskSignals(accumulatedRiskSignals).build();context.appendStateReducerResult(reduced);return context;}
    private StateReducerResult copyOf(StateReducerResult previous){return StateReducerResult.builder().reducedSlots(copyReducedSlots(previous.getReducedSlots(),null)).complaintTruth(copyComplaint(previous.getComplaintTruth())).answeredSlots(previous.getAnsweredSlots()==null?new ArrayList<>():new ArrayList<>(previous.getAnsweredSlots())).pendingCandidates(previous.getPendingCandidates()==null?new ArrayList<>():new ArrayList<>(previous.getPendingCandidates())).correctionLog(previous.getCorrectionLog()==null?new ArrayList<>():new ArrayList<>(previous.getCorrectionLog())).accumulatedRiskSignals(previous.getAccumulatedRiskSignals()==null?new ArrayList<>():new ArrayList<>(previous.getAccumulatedRiskSignals())).build();}
    private Map<SlotCode,SlotValue> copyReducedSlots(Map<SlotCode,SlotValue> reducedSlots,SlotState slotState){Map<SlotCode,SlotValue> result=new EnumMap<>(SlotCode.class);if(slotState!=null&&slotState.getSlots()!=null)result.putAll(slotState.getSlots());if(reducedSlots!=null)result.putAll(reducedSlots);return result;}
    private ComplaintUnderstanding mergeComplaintTruth(ComplaintUnderstanding existing,ComplaintUnderstanding candidate){if(isBlankComplaint(candidate))return existing;String normalized=candidate.getValue().trim();if(isBlankComplaint(existing)||!normalized.equals(existing.getValue()))return ComplaintUnderstanding.builder().value(normalized).confidence(candidate.getConfidence()).evidence(candidate.getEvidence()).build();return existing;}
    private ComplaintUnderstanding copyComplaint(ComplaintUnderstanding complaint){if(complaint==null)return null;return ComplaintUnderstanding.builder().value(complaint.getValue()).confidence(complaint.getConfidence()).evidence(complaint.getEvidence()).build();}
    private void mergePrimaryComplaint(Map<SlotCode,SlotValue> reducedSlots,LinkedHashSet<SlotCode> pendingCandidates,ComplaintUnderstanding complaint){if(isBlankComplaint(complaint))return;SlotValue existing=reducedSlots.get(SlotCode.PRIMARY_SYMPTOM);String complaintValue=complaint.getValue().trim();SlotStatus status=existing!=null&&existing.getValue()!=null&&!existing.getValue().equals(complaintValue)?SlotStatus.CORRECTED:SlotStatus.FILLED;reducedSlots.put(SlotCode.PRIMARY_SYMPTOM,SlotValue.builder().slot(SlotCode.PRIMARY_SYMPTOM).value(complaintValue).status(status).evidence(complaint.getEvidence()).updatedAt(Instant.now()).build());pendingCandidates.remove(SlotCode.PRIMARY_SYMPTOM);}
    private void mergeAnsweredSlots(Map<SlotCode,SlotValue> reducedSlots,LinkedHashSet<SlotCode> answeredSlots,LinkedHashSet<SlotCode> pendingCandidates,List<AnsweredSlotUnderstanding> answeredSlotUnderstandings){if(answeredSlotUnderstandings==null||answeredSlotUnderstandings.isEmpty())return;for(AnsweredSlotUnderstanding answered:answeredSlotUnderstandings){if(answered==null||answered.getSlot()==null)continue;answeredSlots.add(answered.getSlot());SlotStatus slotStatus=resolveSlotStatus(answered);if(isResolved(slotStatus))pendingCandidates.remove(answered.getSlot());reducedSlots.put(answered.getSlot(),SlotValue.builder().slot(answered.getSlot()).value(resolveSlotValue(answered)).status(slotStatus).evidence(answered.getEvidence()).updatedAt(Instant.now()).build());}}
    private void mergeRiskSignals(List<RiskSignalUnderstanding> accumulatedRiskSignals,List<RiskSignalUnderstanding> riskSignals){if(riskSignals==null||riskSignals.isEmpty())return;for(RiskSignalUnderstanding riskSignal:riskSignals){if(riskSignal==null)continue;boolean exists=accumulatedRiskSignals.stream().anyMatch(existing->sameRiskSignal(existing,riskSignal));if(!exists)accumulatedRiskSignals.add(riskSignal);}}
    private void mergeFacts(Map<SlotCode,SlotValue> reducedSlots,LinkedHashSet<SlotCode> answeredSlots,LinkedHashSet<SlotCode> pendingCandidates,List<Fact> facts,int latestTurnIndex,TurnUnderstanding understanding,ComplaintUnderstanding complaintTruth){if(facts==null||facts.isEmpty())return;for(Fact fact:facts){if(fact==null||fact.getSlot()==null||fact.getCanonicalValue()==null)continue;if(fact.getSourceTurnIndex()!=null&&fact.getSourceTurnIndex()!=latestTurnIndex)continue;if(!shouldUseFactAsCompatibilityFallback(reducedSlots,understanding,fact,complaintTruth))continue;SlotStatus slotStatus=resolveFactStatus(fact);reducedSlots.put(fact.getSlot(),SlotValue.builder().slot(fact.getSlot()).value(fact.getCanonicalValue()).status(slotStatus).evidence(fact.getEvidence()).updatedAt(Instant.now()).build());answeredSlots.add(fact.getSlot());if(isResolved(slotStatus))pendingCandidates.remove(fact.getSlot());}}
    private boolean shouldUseFactAsCompatibilityFallback(Map<SlotCode,SlotValue> reducedSlots,TurnUnderstanding understanding,Fact fact,ComplaintUnderstanding complaintTruth){if(fact==null||fact.getSlot()==null)return false;SlotValue existing=reducedSlots.get(fact.getSlot());if(existing!=null&&isResolved(existing.getStatus())&&existing.getValue()!=null&&!existing.getValue().isBlank())return false;if(understanding==null)return fact.getSlot()!=SlotCode.PRIMARY_SYMPTOM||isBlankComplaint(complaintTruth);if(fact.getSlot()==SlotCode.PRIMARY_SYMPTOM)return isBlankComplaint(complaintTruth)&&isBlankComplaint(understanding.getPrimaryComplaint());if(understanding.getAnsweredSlots()==null||understanding.getAnsweredSlots().isEmpty())return true;return understanding.getAnsweredSlots().stream().noneMatch(answered->answered!=null&&answered.getSlot()==fact.getSlot());}
    private SlotStatus resolveFactStatus(Fact fact){if(fact==null||fact.getPolarity()==null)return SlotStatus.FILLED;return fact.getPolarity()==FactPolarity.NEGATIVE?SlotStatus.NEGATED:SlotStatus.FILLED;}
    private void reconcilePendingCandidates(Map<SlotCode,SlotValue> reducedSlots,LinkedHashSet<SlotCode> pendingCandidates){pendingCandidates.removeIf(slotCode->{SlotValue slotValue=reducedSlots.get(slotCode);return slotValue!=null&&isResolved(slotValue.getStatus());});}
    private boolean sameRiskSignal(RiskSignalUnderstanding left,RiskSignalUnderstanding right){if(left==null||right==null)return false;return left.getType()==right.getType()&&left.getAssertion()==right.getAssertion()&&stringEquals(left.getEvidence(),right.getEvidence());}
    private String resolveSlotValue(AnsweredSlotUnderstanding answered){if(answered.getAssertion()==AssertionStatus.ABSENT)return "NO";if((answered.getAssertion()==AssertionStatus.PRESENT||answered.getAssertion()==AssertionStatus.CORRECTED)&&isBooleanLikeSlot(answered.getSlot())&&(answered.getNormalizedValue()==null||answered.getNormalizedValue().isBlank()))return "YES";if(answered.getNormalizedValue()!=null&&!answered.getNormalizedValue().isBlank())return answered.getNormalizedValue().trim();if(answered.getRawValue()!=null&&!answered.getRawValue().isBlank())return answered.getRawValue().trim();return null;}
    private SlotStatus resolveSlotStatus(AnsweredSlotUnderstanding answered){if(answered==null||answered.getAssertion()==null)return SlotStatus.UNKNOWN;return switch(answered.getAssertion()){case PRESENT->SlotStatus.FILLED;case ABSENT->SlotStatus.NEGATED;case CORRECTED->SlotStatus.CORRECTED;case SUSPECTED->SlotStatus.INFERRED;case UNKNOWN->SlotStatus.UNKNOWN;};}
    private boolean isBooleanLikeSlot(SlotCode slotCode){return slotCode==SlotCode.FEVER_PRESENCE||slotCode==SlotCode.NAUSEA_PRESENCE||slotCode==SlotCode.VOMITING_PRESENCE||slotCode==SlotCode.DYSPNEA_PRESENCE||slotCode==SlotCode.BLEEDING_PRESENCE||slotCode==SlotCode.PREGNANCY_STATUS||slotCode==SlotCode.SEIZURE_PRESENCE||slotCode==SlotCode.DIARRHEA_PRESENCE;}
    private boolean isResolved(SlotStatus slotStatus){return slotStatus==SlotStatus.FILLED||slotStatus==SlotStatus.NEGATED||slotStatus==SlotStatus.CORRECTED||slotStatus==SlotStatus.INFERRED;}
    private boolean stringEquals(String left,String right){if(left==null)return right==null;return left.equals(right);} 
    private boolean isBlankComplaint(ComplaintUnderstanding complaint){return complaint==null||complaint.getValue()==null||complaint.getValue().isBlank();}}
